// <auto-generated />
using System;
using Configuration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfigurationHub.Data.Migrations
{
    [DbContext(typeof(ConfigurationContext))]
    [Migration("20201225180625_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Configuration.Domain.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SystemId");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("Configuration.Domain.ConfigAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfigAuthors");
                });

            modelBuilder.Entity("Configuration.Domain.ConfigContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId")
                        .IsUnique();

                    b.ToTable("ConfigContents");
                });

            modelBuilder.Entity("Configuration.Domain.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MicroserviceName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfigSystems");
                });

            modelBuilder.Entity("Configuration.Domain.Config", b =>
                {
                    b.HasOne("Configuration.Domain.ConfigAuthor", "Author")
                        .WithMany("Configs")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Configuration.Domain.System", "System")
                        .WithMany("Configs")
                        .HasForeignKey("SystemId");

                    b.Navigation("Author");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Configuration.Domain.ConfigContent", b =>
                {
                    b.HasOne("Configuration.Domain.Config", "Config")
                        .WithOne("ConfigContent")
                        .HasForeignKey("Configuration.Domain.ConfigContent", "ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("Configuration.Domain.Config", b =>
                {
                    b.Navigation("ConfigContent");
                });

            modelBuilder.Entity("Configuration.Domain.ConfigAuthor", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("Configuration.Domain.System", b =>
                {
                    b.Navigation("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
