// <auto-generated />
using System;
using Configuration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfigurationHub.Data.Migrations
{
    [DbContext(typeof(ConfigurationContext))]
    [Migration("20210202192052_ConfigIndexes")]
    partial class ConfigIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ConfigurationHub.Domain.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Username", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MicroserviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LastModified");

                    b.HasIndex("MicroserviceId");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.Content.ConfigContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId")
                        .IsUnique();

                    b.ToTable("ConfigContents");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.MicroserviceModels.Microservice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SystemId");

                    b.ToTable("MicroServices");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.SystemModels.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.Config", b =>
                {
                    b.HasOne("ConfigurationHub.Domain.Auth.User", "Author")
                        .WithMany("Configs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigurationHub.Domain.ConfigModels.MicroserviceModels.Microservice", "Microservice")
                        .WithMany("Configs")
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Microservice");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.Content.ConfigContent", b =>
                {
                    b.HasOne("ConfigurationHub.Domain.ConfigModels.Config", "Config")
                        .WithOne("ConfigContent")
                        .HasForeignKey("ConfigurationHub.Domain.ConfigModels.Content.ConfigContent", "ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.MicroserviceModels.Microservice", b =>
                {
                    b.HasOne("ConfigurationHub.Domain.ConfigModels.SystemModels.System", "System")
                        .WithMany("Microservices")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.Auth.User", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.Config", b =>
                {
                    b.Navigation("ConfigContent")
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.MicroserviceModels.Microservice", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("ConfigurationHub.Domain.ConfigModels.SystemModels.System", b =>
                {
                    b.Navigation("Microservices");
                });
#pragma warning restore 612, 618
        }
    }
}
